SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[newview]'
GO
IF OBJECT_ID(N'[dbo].[newview]', 'V') IS NOT NULL
DROP VIEW [dbo].[newview]
GO
PRINT N'Altering [dbo].[DM_CUSTOMER_NOTES]'
GO
IF COL_LENGTH(N'[dbo].[DM_CUSTOMER_NOTES]', N'status') IS NOT NULL
ALTER TABLE [dbo].[DM_CUSTOMER_NOTES] DROP COLUMN [status]
GO
PRINT N'Creating [dbo].[oldproc]'
GO
IF OBJECT_ID(N'[dbo].[oldproc]', 'P') IS NULL
EXEC sp_executesql N'--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--GO
CREATE PROCEDURE [dbo].[oldproc]
    @parameter_name AS INT
-- WITH ENCRYPTION, RECOMPILE, EXECUTE AS CALLER|SELF|OWNER| ''user_name''
AS
BEGIN
    SELECT * FROM dbo.DM_CUSTOMER AS DC
END
'
GO

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

