SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[oldproc]'
GO
IF OBJECT_ID(N'[dbo].[oldproc]', 'P') IS NOT NULL
DROP PROCEDURE [dbo].[oldproc]
GO
PRINT N'Altering [dbo].[DM_CUSTOMER_NOTES]'
GO
IF COL_LENGTH(N'[dbo].[DM_CUSTOMER_NOTES]', N'status') IS NULL
ALTER TABLE [dbo].[DM_CUSTOMER_NOTES] ADD[status] [int] NULL
GO
PRINT N'Creating [dbo].[newview]'
GO
IF OBJECT_ID(N'[dbo].[newview]', 'V') IS NULL
EXEC sp_executesql N'CREATE VIEW [dbo].[newview]
--WITH ENCRYPTION, SCHEMABINDING, VIEW_METADATA
AS
    SELECT * FROM dbo.DM_CUSTOMER
-- WITH CHECK OPTION
'
GO

SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
SET DATEFORMAT YMD
GO
SET XACT_ABORT ON
GO

